[32mINFO    [0m integration.test_backups:test_backups.py:67 deleting the previously created backups
[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.1.7    unsupported  01:57:24Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Exposed  Message
postgresql-aws            14.11    active      2  postgresql                                 0  no       
s3-integrator                      active      1  s3-integrator             latest/stable   17  no       
self-signed-certificates           active      1  self-signed-certificates  latest/stable   72  no       

Unit                         Workload     Agent      Machine  Public address  Ports     Message
postgresql-aws/0*            maintenance  executing  2        10.163.174.182  5432/tcp  initialising stanza
postgresql-aws/1             waiting      idle       3        10.163.174.89   5432/tcp  awaiting for cluster to start
s3-integrator/0*             active       idle       0        10.163.174.245            
self-signed-certificates/0*  active       idle       1        10.163.174.142            

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.163.174.245  juju-805a2f-0  ubuntu@22.04      Running
1        started  10.163.174.142  juju-805a2f-1  ubuntu@22.04      Running
2        started  10.163.174.182  juju-805a2f-2  ubuntu@22.04      Running
3        started  10.163.174.89   juju-805a2f-3  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:

machine-1: 01:37:11 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:37:11 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-1: 01:37:11 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-self-signed-certificates-0: 01:37:11 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:37:13 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:37:13 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-0: 01:37:13 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-s3-integrator-0: 01:37:13 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:37:21 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-2: 01:37:21 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:37:21 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-aws-0: 01:37:21 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:37:24 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:37:24 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-3: 01:37:24 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-aws-1: 01:37:24 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-aws-0: 01:56:50 ERROR unit.postgresql-aws/0.juju-log database-peers:2: RetryError[<Future at 0x7f8662a56ec0 state=finished raised Exception>]
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-aws-0/charm/src/backups.py", line 447, in check_stanza
    raise Exception(stderr)
Exception: WARN: unable to check pg2: [HostConnectError] unable to connect to '10.163.174.89:8432': [111] Connection refused
          [HostConnectError] on 12 retries from 101-60001ms: unable to connect to '10.163.174.89:8432': [111] Connection refused
ERROR: [049]: unable to connect to '10.163.174.89:8432': [111] Connection refused
           [HostConnectError] on 12 retries from 100-60000ms: unable to connect to '10.163.174.89:8432': [111] Connection refused


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-aws-0/charm/src/backups.py", line 436, in check_stanza
    for attempt in Retrying(stop=stop_after_attempt(5), wait=wait_fixed(3)):
  File "/var/lib/juju/agents/unit-postgresql-aws-0/charm/venv/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-postgresql-aws-0/charm/venv/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f8662a56ec0 state=finished raised Exception>]

[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...